name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy ruff langdetect

    - name: Run MyPy type checking
      run: |
        mypy comment_extractor.py merger.py tree_generater.py --ignore-missing-imports

    - name: Run Ruff linting
      run: |
        ruff check comment_extractor.py merger.py tree_generater.py

    - name: Run Ruff formatting check
      run: |
        ruff format comment_extractor.py merger.py tree_generater.py --check

  test-scripts:
    name: Test Scripts Functionality
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install langdetect

    - name: Test comment_extractor help
      run: |
        python comment_extractor.py --help

    - name: Test merger help
      run: |
        python merger.py --help

    - name: Test tree_generater help
      run: |
        python tree_generater.py --help

    - name: Test basic functionality
      run: |
        # Create test files
        mkdir -p test_dir
        echo "# Test Python file" > test_dir/test.py
        echo "// Test C++ file" > test_dir/test.cpp
        
        # Test comment extractor
        python comment_extractor.py test_dir --pattern "*.py" --preview
        
        # Test merger
        python merger.py test_dir/test.py test_dir/test.cpp --preview
        
        # Test tree generator
        python tree_generater.py test_dir --preview

    - name: Cleanup
      if: always()
      run: |
        rm -rf test_dir