name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy ruff

    - name: Run MyPy type checking
      run: |
        mypy comment_extractor.py merger.py tree_generater.py --ignore-missing-imports

    - name: Run Ruff linting
      run: |
        ruff check comment_extractor.py merger.py tree_generater.py

    - name: Run Ruff formatting check
      run: |
        ruff format comment_extractor.py merger.py tree_generater.py --check

  test-installation:
    name: Test Package Installation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install package in development mode
      run: |
        pip install -e .

    - name: Test script availability
      run: |
        python -c "import codingutils; print('Package imported successfully')"
        comment-extractor --help || echo "comment-extractor not found as command"
        file-merger --help || echo "file-merger not found as command"
        project-tree --help || echo "project-tree not found as command"